### ISSUE TITLE
请问怎么配置这个框架的混淆啊？

### ISSUE THREAD

**Issue by zhangnin** [mxdldev/android-mvp-mvvm-flytour#8]
打包出来的apk，安装启动后发现页面什么都没有，连页面的一个view都没有显示，请问这是什么原因造成的，混淆文件需要过滤这个框架的什么配置吗？

**Comment by zjlooong** [comment]
大哥你发错人了吧，我做web的&nbsp; 不懂Android




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhangning"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 中午11:03
收件人:&nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8)




打包出来的apk，安装启动后发现页面什么都没有，连页面的一个view都没有显示，请问这是什么原因造成的，混淆文件需要过滤这个框架的什么配置吗？

**Comment by swift513** [comment]
你发错人了，我搞web的------------------ 原始邮件 ------------------
发件人: "zjlooong"<notifications@github.com>
发送时间: 2020年2月12日(星期三) 中午11:08
收件人: "mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8)


大哥你发错人了吧，我做web的&nbsp; 不懂Android 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"zhangning"<notifications@github.com&gt;; 
 发送时间:&nbsp;2020年2月12日(星期三) 中午11:03 
 收&#x4EF6;人:&nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&gt;; 
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 
 主题:&nbsp;[mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8) 
 
 
 
 
 打包出来的apk，安装启动后发现页面什么都没有，连页面的一个view都没有显示，请问这是什么原因造成的，混淆文&#x4EF6;需要过滤这个框架的什么配置吗？ 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by zhangnin** [comment]
可以了，路由混淆问题：

-keep public class com.alibaba.android.arouter.routes.**{*;}
-keep public class com.alibaba.android.arouter.facade.**{*;}
-keep class * implements com.alibaba.android.arouter.facade.template.ISyringe{*;}

# If you use the byType method to obtain Service, add the following rules to protect the interface:
-keep interface * implements com.alibaba.android.arouter.facade.template.IProvider

# If single-type injection is used, that is, no interface is defined to implement IProvider, the following rules need to be added to protect the implementation
# -keep class * implements com.alibaba.android.arouter.facade.template.IProvider

**Comment by y1260180780** [comment]
大哥，怎么搞到我邮箱的，我是搞Java的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zjlooong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 中午11:09
收件人:&nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8)



大哥你发错人了吧，我做web的&amp;nbsp; 不懂Android 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"zhangning"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月12日(星期三) 中午11:03 
 收件人:&amp;nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8) 
 
 
 
 
 打包出来的apk，安装启动后发现页面什么都没有，连页面的一个view都没有显示，请问这是什么原因造成的，混淆文件需要过滤这个框架的什么配置吗？

**Comment by zhangnin** [comment]
> 大哥，怎么搞到我邮箱的，我是搞Java的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"zjlooong"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月12日(星期三) 中午11:09 收件人:&nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8) 大哥你发错人了吧，我做web的&amp;nbsp; 不懂Android
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人:&amp;nbsp;"zhangning"<notifications@github.com&amp;gt;; 发送时间:&amp;nbsp;2020年2月12日(星期三) 中午11:03 收件人:&amp;nbsp;"mxdldev/android-mvp-mvvm-flytour"<android-mvp-mvvm-flytour@noreply.github.com&amp;gt;; 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 主题:&amp;nbsp;[mxdldev/android-mvp-mvvm-flytour] 请问怎么配置这个框架的混淆啊？ (#8) 打包出来的apk，安装启动后发现页面什么都没有，连页面的一个view都没有显示，请问这是什么原因造成的，混淆文件需要过滤这个框架的什么配置吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不知道，我是在这里留言，建了个issues。
